/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lexer;

import java.io.File;
import java.io.StringReader;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import static lexer.Lexer.n_column;
import static lexer.Lexer.n_line;


/**
 *
 * @author daniel
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    
    public JTextArea jText;
    public String fileName = "";
    public String filePath = "";
    public TS tabelaSimbolos;
    
    
    
    // metodo executar
    public void executar(String filePath) throws Exception { 
     
        int cont = 0;     
        
        Lexer lexer = new Lexer(filePath);
        
        lexer.leituraArquivoToken(textArea1, textArea2);
        
    }
    
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(this);
        Look.definelook(this);
        //setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        btnAnexar = new javax.swing.JButton();
        lb_entrada = new javax.swing.JLabel();
        lb_analiseLexica = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        btnAnalisar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea2 = new javax.swing.JTextArea();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAnexar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAnexar.setForeground(new java.awt.Color(153, 0, 51));
        btnAnexar.setText("Anexar Arquivo PasC");
        btnAnexar.setBorder(new javax.swing.border.MatteBorder(null));
        btnAnexar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnexarActionPerformed(evt);
            }
        });

        lb_entrada.setBackground(new java.awt.Color(51, 153, 0));
        lb_entrada.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lb_entrada.setForeground(new java.awt.Color(153, 0, 51));
        lb_entrada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_entrada.setText("Nome do Arquivo");
        lb_entrada.setToolTipText("");
        lb_entrada.setBorder(new javax.swing.border.MatteBorder(null));
        lb_entrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lb_analiseLexica.setBackground(new java.awt.Color(102, 102, 0));
        lb_analiseLexica.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lb_analiseLexica.setForeground(new java.awt.Color(153, 51, 0));
        lb_analiseLexica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_analiseLexica.setText("Análise Léxica");
        lb_analiseLexica.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        btnLimpar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(153, 0, 51));
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(new javax.swing.border.MatteBorder(null));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        textArea1.setEditable(false);
        textArea1.setColumns(20);
        textArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textArea1.setRows(5);
        jScrollPane1.setViewportView(textArea1);

        btnAnalisar1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAnalisar1.setForeground(new java.awt.Color(153, 0, 51));
        btnAnalisar1.setText("Analisar");
        btnAnalisar1.setBorder(new javax.swing.border.MatteBorder(null));
        btnAnalisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisar1ActionPerformed(evt);
            }
        });

        textArea2.setEditable(false);
        textArea2.setColumns(20);
        textArea2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textArea2.setRows(5);
        jScrollPane2.setViewportView(textArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_analiseLexica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lb_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnexar, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnalisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(226, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_analiseLexica)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnexar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(124, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnexarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnexarActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        File workingDirectory = new File(System.getProperty("user.dir"));
        chooser.setCurrentDirectory(workingDirectory);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filePath = f.getAbsolutePath();
        fileName = f.getName();
        lb_entrada.setText(fileName);
    }//GEN-LAST:event_btnAnexarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // ira apenas apagar o que foi inserido nos resultados
//        entrada.setText("");
        filePath = "";
        lb_entrada.setText("Nome do Arquivo");
        textArea1.setText("");
        textArea2.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAnalisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisar1ActionPerformed

        //chamada do metod executar
        try{
            
            if(filePath.equals("")){
                
                textArea2.setText("ANEXE UM ARQUIVO EM PASC PARA ANÁLISE");
                
            } else {
                
                executar(filePath);
            }
            
        }catch(Exception e){
            
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_btnAnalisar1ActionPerformed

    /**
     * @param args the command line arguments
     */
                                            
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalisar1;
    private javax.swing.JButton btnAnexar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_analiseLexica;
    private javax.swing.JLabel lb_entrada;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JTextArea textArea2;
    // End of variables declaration//GEN-END:variables
}
