/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sool.*;


/**
 *
 * @author danih
 */
public class AddPeriodo extends javax.swing.JFrame {

    public Curso curso;
    public int i;
    public Ciclo ciclo;
    private Arquivo arquivo;
    
    public AddPeriodo(Curso c) {
        this.arquivo = new Arquivo();
        this.curso = c;
        initComponents();
        centreWindow(this);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) { 
                new SOOL().setVisible(true);
            }
        });
    }
    
     public boolean checkIfCodigoAlreadyExists(String codigo){
        
        for(Ciclo e : arquivo.readPeriodo("periodo")){ 
            if(e.getDescTema().equalsIgnoreCase(codigo) && 
                    e.getCurso().getCodigo().equalsIgnoreCase(curso.getCodigo())){
                return true;
            }
        }
        
        return false;
        
    }

    public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }
    
    public static boolean isNumeric(String str){
        for (char c : str.toCharArray()){
            if (!Character.isDigit(c)) return false;
        }
        return true;
    }
    
    public int showConfirmDialog(String message, String title){
       
        Object[] options = {"OK"};
        int n = 0;
        
        n = JOptionPane.showOptionDialog(null,
            message, 
            title,
            JOptionPane.PLAIN_MESSAGE,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]); 
        
        return n;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_analiseLexica1 = new javax.swing.JLabel();
        lb_analiseLexica2 = new javax.swing.JLabel();
        confirmarPeriodos = new javax.swing.JButton();
        textPeriodo = new javax.swing.JTextField();

        lb_analiseLexica1.setBackground(new java.awt.Color(102, 102, 0));
        lb_analiseLexica1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lb_analiseLexica1.setForeground(new java.awt.Color(153, 51, 0));
        lb_analiseLexica1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_analiseLexica1.setText("Sistema - SOOL");
        lb_analiseLexica1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_analiseLexica2.setBackground(new java.awt.Color(102, 102, 0));
        lb_analiseLexica2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lb_analiseLexica2.setForeground(new java.awt.Color(153, 51, 0));
        lb_analiseLexica2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_analiseLexica2.setText("Digite o código do período");
        lb_analiseLexica2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        confirmarPeriodos.setText("Adicionar");
        confirmarPeriodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarPeriodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmarPeriodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_analiseLexica2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(textPeriodo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_analiseLexica2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(confirmarPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarPeriodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarPeriodosActionPerformed
        
        String qtdPeriodos = textPeriodo.getText().toString().trim();
        
        if(!qtdPeriodos.isEmpty()){
            if(isNumeric(qtdPeriodos)){
                if(!checkIfCodigoAlreadyExists(qtdPeriodos)){
                    if(Integer.parseInt(qtdPeriodos) <= 12){
                        try {
                            ciclo = new Ciclo(curso, qtdPeriodos);
                            arquivo.savePeriodo("periodo", Ciclo.listCiclos);
                            if(showConfirmDialog("Período adicionado!", "Alerta") ==
                                    JOptionPane.OK_OPTION){
                                textPeriodo.setText("");
                            }
                        } catch (Exception ex) {
                            System.out.println(ex.getMessage());
                        }
                    } else {
                        showConfirmDialog("Código não pode ser superior a 12 (Número Máximo)"
                                + " exceder a 12", "Alerta");
                    }    
                } else {
                    showConfirmDialog("Digite um código de período diferente pra esse curso", "Alerta");    
                }
            } else {
                showConfirmDialog("Digite um valor numérico", "Alerta");
            }
        } else {
            showConfirmDialog("Preencha os campos!", "Alerta");
        }       
    }//GEN-LAST:event_confirmarPeriodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmarPeriodos;
    private javax.swing.JLabel lb_analiseLexica1;
    private javax.swing.JLabel lb_analiseLexica2;
    private javax.swing.JTextField textPeriodo;
    // End of variables declaration//GEN-END:variables
}
