/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import static jFrames.ViewCursosFrame.centreWindow;
import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import sool.*;

/**
 *
 * @author danih
 */
public class ExtensaoPeriodoFrame extends javax.swing.JFrame {
    
    private int width = 620;
    private int height = 340;
    public JList<String> jList = new JList<>();
    public String codigoGraduacao = ""; 
    public boolean isEmpty;
    public boolean exists = false;
    public boolean isEmptyExtensao;
    public boolean existsExtensao = false;
    
    public ExtensaoPeriodoFrame() {
        initPanel();
        initComponents();
        showCursos();
        centreWindow(this);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) { 
                new SOOL().setVisible(true);
            }
        });
    }
    
    public void initPanel(){
        add(createMainPanel());
        setTitle("Lista de Cursos de Extensão");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(width, height);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    private JPanel createMainPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(new EmptyBorder(10, 10, 10, 10));
        panel.add(new JScrollPane(jList = showCursos()), BorderLayout.CENTER);
        return panel;
    }
    
    public JList<String> showCursos(){
        
        DefaultListModel<String> model = new DefaultListModel<>();
        
        Extensao.listaExtensao = new Arquivo().readExtensao("extensao");
        
        if(Extensao.listaExtensao.isEmpty()){
            model.addElement("NENHUM CURSO DE EXTENSÃO NO SISTEMA!");
        } else {
            for(int i = 0; i < Extensao.listaExtensao.size(); i++){
                model.addElement(
                        "CÓDIGO: " + Extensao.listaExtensao.get(i).getCodigo().toUpperCase() + 
                        " - NOME: " + Extensao.listaExtensao.get(i).getNome().toUpperCase() + 
                        " - TURNO: " + Extensao.listaExtensao.get(i).getTurno().toUpperCase()
                );            
            }    
        }
        
        JList<String> list = new JList<String>(model);  
        
        list.setFont(new Font("Arial", Font.BOLD, 16));
        
        jListItemClickEvent(list);
               
        return list;
        
    }
    
    public void showExistsCodigo(boolean exists, boolean isEmpty){
        
        Object[] options = {"OK"};
        
        if(exists == false && isEmpty == false){
            JOptionPane.showOptionDialog(null,
            "Código do Curso de Extensão não existe no Sistema!",
            "Confirmação",
            JOptionPane.PLAIN_MESSAGE,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]);    
        } else if(isEmpty == true) {
            JOptionPane.showOptionDialog(null,
            "Ainda não existe cursos de Extensão adicionadas ao Sistema!",
            "Confirmação",
            JOptionPane.PLAIN_MESSAGE,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCurso = new javax.swing.JLabel();
        selectCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbCurso.setBackground(new java.awt.Color(102, 102, 0));
        lbCurso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbCurso.setForeground(new java.awt.Color(153, 51, 0));
        lbCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCurso.setText("Escolha um curso de Extensão");
        lbCurso.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        selectCurso.setText("Selecionar Curso");
        selectCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(selectCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(lbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(selectCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCursoActionPerformed

        isEmpty = false;

        if(Extensao.listaExtensao.isEmpty()){
            isEmpty = true;
        }

        for(Extensao e : Extensao.listaExtensao){
            if(e.getCodigo().equalsIgnoreCase(codigoGraduacao)){
                AddPeriodo addPeriodo = new AddPeriodo(e);
                addPeriodo.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                addPeriodo.setVisible(true);
                this.setVisible(false);
                exists = true;
                isEmpty = false;
                break;
            }
        }

        showExistsCodigo(exists, isEmpty);

    }//GEN-LAST:event_selectCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtensaoPeriodoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtensaoPeriodoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtensaoPeriodoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtensaoPeriodoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExtensaoPeriodoFrame().setVisible(true);
            }
        });
    }
    
    private void jListItemClickEvent(JList dataList) {
        
        dataList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    String value = dataList.getSelectedValue().toString();
                    if(value.contains("-")){
                        System.out.println("Valor: " + value);
                        codigoGraduacao = value.
                                substring(value.indexOf(':') + 1, value.indexOf('-')).trim();    
                        System.out.println(codigoGraduacao); 
                    } else {
                        codigoGraduacao = "";
                        isEmpty = true;
                    }
                    lbCurso.setText(value);
                }
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCurso;
    private javax.swing.JButton selectCurso;
    // End of variables declaration//GEN-END:variables
}
