/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;

/**
 *
 * @author danih
 */
public class GradOrExtentPeriodo extends javax.swing.JFrame {

    /**
     * Creates new form GradOrExtentPeriodo
     */
    public GradOrExtentPeriodo() {
        initComponents();
        centreWindow(this);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) { 
                new SOOL().setVisible(true);
            }
        });
    }
    
    public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addGrad = new javax.swing.JButton();
        lb_analiseLexica1 = new javax.swing.JLabel();
        setGrad = new javax.swing.JButton();
        setExtensao = new javax.swing.JButton();

        addGrad.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        addGrad.setForeground(new java.awt.Color(153, 0, 51));
        addGrad.setText("Graduação");
        addGrad.setBorder(new javax.swing.border.MatteBorder(null));
        addGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGradActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_analiseLexica1.setBackground(new java.awt.Color(102, 102, 0));
        lb_analiseLexica1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lb_analiseLexica1.setForeground(new java.awt.Color(153, 51, 0));
        lb_analiseLexica1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_analiseLexica1.setText("Escolha um tipo");
        lb_analiseLexica1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        setGrad.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        setGrad.setForeground(new java.awt.Color(153, 0, 51));
        setGrad.setText("Graduação");
        setGrad.setBorder(new javax.swing.border.MatteBorder(null));
        setGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setGradActionPerformed(evt);
            }
        });

        setExtensao.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        setExtensao.setForeground(new java.awt.Color(153, 0, 51));
        setExtensao.setText("Extensao");
        setExtensao.setBorder(new javax.swing.border.MatteBorder(null));
        setExtensao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setExtensaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_analiseLexica1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(setGrad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(setExtensao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_analiseLexica1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setExtensao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGradActionPerformed

    }//GEN-LAST:event_addGradActionPerformed

    private void setGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setGradActionPerformed
        PeriodoFrame periodoFrame = new PeriodoFrame();
        periodoFrame.setVisible(true);
        periodoFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_setGradActionPerformed

    private void setExtensaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setExtensaoActionPerformed
        ExtensaoPeriodoFrame periodoFrame = new ExtensaoPeriodoFrame();
        periodoFrame.setVisible(true);
        periodoFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_setExtensaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradOrExtentPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradOrExtentPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradOrExtentPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradOrExtentPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradOrExtentPeriodo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGrad;
    private javax.swing.JLabel lb_analiseLexica1;
    private javax.swing.JButton setExtensao;
    private javax.swing.JButton setGrad;
    // End of variables declaration//GEN-END:variables
}
