/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;

public class SOOL extends javax.swing.JFrame {

    public SOOL() {
        initComponents();
        centreWindow(this);
    }
    
    public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_analiseLexica1 = new javax.swing.JLabel();
        adicionarCurso = new javax.swing.JButton();
        lb_analiseLexica2 = new javax.swing.JLabel();
        lb_analiseLexica3 = new javax.swing.JLabel();
        btnAdicionarDisciplina = new javax.swing.JButton();
        btnVerCursos = new javax.swing.JButton();
        lb_analiseLexica4 = new javax.swing.JLabel();
        btnAdicionarPeriodo = new javax.swing.JButton();
        lb_analiseLexica5 = new javax.swing.JLabel();
        btnAdicionarAlunos = new javax.swing.JButton();
        lb_analiseLexica6 = new javax.swing.JLabel();
        btnAdicionarTurma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_analiseLexica1.setBackground(new java.awt.Color(102, 102, 0));
        lb_analiseLexica1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lb_analiseLexica1.setForeground(new java.awt.Color(153, 51, 0));
        lb_analiseLexica1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_analiseLexica1.setText("Sistema - SOOL");
        lb_analiseLexica1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_analiseLexica1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_analiseLexica1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        adicionarCurso.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        adicionarCurso.setForeground(new java.awt.Color(153, 0, 51));
        adicionarCurso.setText("Adicionar Curso");
        adicionarCurso.setBorder(new javax.swing.border.MatteBorder(null));
        adicionarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCursoActionPerformed(evt);
            }
        });

        lb_analiseLexica2.setBackground(new java.awt.Color(102, 102, 0));
        lb_analiseLexica2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_analiseLexica2.setForeground(new java.awt.Color(153, 51, 0));
        lb_analiseLexica2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_analiseLexica2.setText("Disciplina");
        lb_analiseLexica2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        lb_analiseLexica3.setBackground(new java.awt.Color(102, 102, 0));
        lb_analiseLexica3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_analiseLexica3.setForeground(new java.awt.Color(153, 51, 0));
        lb_analiseLexica3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_analiseLexica3.setText("Cursos");
        lb_analiseLexica3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        btnAdicionarDisciplina.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAdicionarDisciplina.setForeground(new java.awt.Color(153, 0, 51));
        btnAdicionarDisciplina.setText("Adicionar Disciplina");
        btnAdicionarDisciplina.setBorder(new javax.swing.border.MatteBorder(null));
        btnAdicionarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarDisciplinaActionPerformed(evt);
            }
        });

        btnVerCursos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnVerCursos.setForeground(new java.awt.Color(153, 0, 51));
        btnVerCursos.setText("Ver Cursos");
        btnVerCursos.setBorder(new javax.swing.border.MatteBorder(null));
        btnVerCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCursosActionPerformed(evt);
            }
        });

        lb_analiseLexica4.setBackground(new java.awt.Color(102, 102, 0));
        lb_analiseLexica4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_analiseLexica4.setForeground(new java.awt.Color(153, 51, 0));
        lb_analiseLexica4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_analiseLexica4.setText("Periodo");
        lb_analiseLexica4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        btnAdicionarPeriodo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAdicionarPeriodo.setForeground(new java.awt.Color(153, 0, 51));
        btnAdicionarPeriodo.setText("Adicionador Periodo");
        btnAdicionarPeriodo.setBorder(new javax.swing.border.MatteBorder(null));
        btnAdicionarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPeriodoActionPerformed(evt);
            }
        });

        lb_analiseLexica5.setBackground(new java.awt.Color(102, 102, 0));
        lb_analiseLexica5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_analiseLexica5.setForeground(new java.awt.Color(153, 51, 0));
        lb_analiseLexica5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_analiseLexica5.setText("Alunos");
        lb_analiseLexica5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        btnAdicionarAlunos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAdicionarAlunos.setForeground(new java.awt.Color(153, 0, 51));
        btnAdicionarAlunos.setText("Adicionar Alunos");
        btnAdicionarAlunos.setBorder(new javax.swing.border.MatteBorder(null));
        btnAdicionarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAlunosActionPerformed(evt);
            }
        });

        lb_analiseLexica6.setBackground(new java.awt.Color(102, 102, 0));
        lb_analiseLexica6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_analiseLexica6.setForeground(new java.awt.Color(153, 51, 0));
        lb_analiseLexica6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_analiseLexica6.setText("Turma");
        lb_analiseLexica6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        btnAdicionarTurma.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAdicionarTurma.setForeground(new java.awt.Color(153, 0, 51));
        btnAdicionarTurma.setText("Adicionar Turma");
        btnAdicionarTurma.setBorder(new javax.swing.border.MatteBorder(null));
        btnAdicionarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionarAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_analiseLexica3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adicionarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_analiseLexica4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionarPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_analiseLexica2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionarDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_analiseLexica6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionarTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_analiseLexica5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_analiseLexica3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adicionarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_analiseLexica4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionarPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_analiseLexica2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lb_analiseLexica6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_analiseLexica5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionarAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCursoActionPerformed
        GradOrExtension gradOrExtension = new GradOrExtension();
        gradOrExtension.setVisible(true);
        gradOrExtension.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);   
    }//GEN-LAST:event_adicionarCursoActionPerformed

    private void btnAdicionarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarDisciplinaActionPerformed
        ExtentOrGradDisciplinaFrame disciplinaFrame = new ExtentOrGradDisciplinaFrame();
        disciplinaFrame.setVisible(true);
        disciplinaFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdicionarDisciplinaActionPerformed

    private void btnVerCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCursosActionPerformed
        GradOrExtenView gradOrExtenView = new GradOrExtenView();
        gradOrExtenView.setVisible(true);
        gradOrExtenView.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_btnVerCursosActionPerformed

    private void btnAdicionarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPeriodoActionPerformed
        GradOrExtentPeriodo periodoFrame = new GradOrExtentPeriodo();
        periodoFrame.setVisible(true);
        periodoFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdicionarPeriodoActionPerformed

    private void btnAdicionarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAlunosActionPerformed
        GradOrExtensaoAluno extenOrGradAluno = new GradOrExtensaoAluno();
        extenOrGradAluno.setVisible(true);
        extenOrGradAluno.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdicionarAlunosActionPerformed

    private void btnAdicionarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTurmaActionPerformed
        ExtensaoOrGradTurma extensaoOrGradTurma = new ExtensaoOrGradTurma();
        extensaoOrGradTurma.setVisible(true);
        extensaoOrGradTurma.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdicionarTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SOOL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SOOL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SOOL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SOOL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new SOOL().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarCurso;
    private javax.swing.JButton btnAdicionarAlunos;
    private javax.swing.JButton btnAdicionarDisciplina;
    private javax.swing.JButton btnAdicionarPeriodo;
    private javax.swing.JButton btnAdicionarTurma;
    private javax.swing.JButton btnVerCursos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_analiseLexica1;
    private javax.swing.JLabel lb_analiseLexica2;
    private javax.swing.JLabel lb_analiseLexica3;
    private javax.swing.JLabel lb_analiseLexica4;
    private javax.swing.JLabel lb_analiseLexica5;
    private javax.swing.JLabel lb_analiseLexica6;
    // End of variables declaration//GEN-END:variables

}
