/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import static jFrames.GradOrExtensaoAluno.centreWindow;
import javax.swing.JOptionPane;
import sool.*;

/**
 *
 * @author danih
 */
public class TurmaDeGraduacaoOrExtensao extends javax.swing.JFrame {

    Object[] options = {"OK"};
    Curso curso;
    Ciclo ciclo;
    Disciplina disciplina;
    
    public TurmaDeGraduacaoOrExtensao(Curso c, Ciclo cl, Disciplina d) {
        this.curso = c;
        this.ciclo = cl;
        this.disciplina = d;
        initComponents();
        centreWindow(this);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) { 
                new SOOL().setVisible(true);
            }
        });     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseTipo = new javax.swing.JLabel();
        btnGraduacaoTurma = new javax.swing.JButton();
        btnExtensaoTurma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chooseTipo.setBackground(new java.awt.Color(102, 102, 0));
        chooseTipo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        chooseTipo.setForeground(new java.awt.Color(153, 51, 0));
        chooseTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseTipo.setText("Escolha uma turma");
        chooseTipo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        btnGraduacaoTurma.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnGraduacaoTurma.setForeground(new java.awt.Color(153, 0, 51));
        btnGraduacaoTurma.setText("Turma de Graduação");
        btnGraduacaoTurma.setBorder(new javax.swing.border.MatteBorder(null));
        btnGraduacaoTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduacaoTurmaActionPerformed(evt);
            }
        });

        btnExtensaoTurma.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnExtensaoTurma.setForeground(new java.awt.Color(153, 0, 51));
        btnExtensaoTurma.setText("Turma de Extensao");
        btnExtensaoTurma.setBorder(new javax.swing.border.MatteBorder(null));
        btnExtensaoTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtensaoTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chooseTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(btnGraduacaoTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExtensaoTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGraduacaoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExtensaoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraduacaoTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduacaoTurmaActionPerformed

        TurmasFrame turmasFrame = new TurmasFrame(ciclo, curso, disciplina);
        turmasFrame.setVisible(true);
        turmasFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnGraduacaoTurmaActionPerformed

    private void btnExtensaoTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtensaoTurmaActionPerformed

        TurmaExtensaoFrame turmasFrame = new TurmaExtensaoFrame(ciclo, curso, disciplina);
        turmasFrame.setVisible(true);
        turmasFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_btnExtensaoTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TurmaDeGraduacaoOrExtensao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TurmaDeGraduacaoOrExtensao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TurmaDeGraduacaoOrExtensao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TurmaDeGraduacaoOrExtensao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExtensaoTurma;
    private javax.swing.JButton btnGraduacaoTurma;
    private javax.swing.JLabel chooseTipo;
    // End of variables declaration//GEN-END:variables
}
