/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import static jFrames.ViewTurmas.centreWindow;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import sool.Aluno;
import sool.Arquivo;
import sool.Ciclo;
import sool.Curso;
import sool.Disciplina;
import sool.Turma;
import sool.TurmaGraduacao;

/**
 *
 * @author danih
 */
public class ViewAlunos extends javax.swing.JFrame {

    public Ciclo ciclo;
    public Curso curso;
    public Disciplina disciplina;
    public Turma turma;
    private int width = 720;
    private int height = 340;
    
    public ViewAlunos(Ciclo ciclo, Curso curso, Disciplina disciplina, Turma turma) {
        this.ciclo = ciclo;
        this.curso = curso;
        this.disciplina = disciplina;
        this.turma = turma;
        System.out.println("Tamanho da lista de alunos: " + Aluno.alunos.size());
        initPanel();
        initComponents();
        showAlunos();
        centreWindow(this);
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) { 
                new SOOL().setVisible(true);
            }
        });
    }
    
    public void initPanel(){
        add(createMainPanel());
        setTitle("Lista de Alunos");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(width, height);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    private JPanel createMainPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(new EmptyBorder(10, 10, 10, 10));
        panel.add(new JScrollPane(showAlunos()), BorderLayout.CENTER);
        return panel;
    }
    
    public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }
    
    public JList<String> showAlunos(){
        
        DefaultListModel<String> model = new DefaultListModel<>();
        
        System.out.println("Curso passado: " + curso.getNome());
        System.out.println("Ciclo passado: " + ciclo.getDescTema());
        System.out.println("Disciplina passada: " + disciplina.getNome());
        System.out.println("Turma passada: " + turma.getCodSequencia());
        
        Aluno.alunos = new Arquivo().readAluno("aluno");
        
        if(Aluno.alunos.isEmpty()){
            model.addElement("NENHUM ALUNO PARA ESTA DISCIPLINA!");
        } else {
            for(int i = 0; i < Aluno.alunos.size(); i++){
                if(String.valueOf(Aluno.alunos.get(i).getTurma().getCodSequencia())
                        .equalsIgnoreCase(String.valueOf(turma.getCodSequencia())) 
                        && Aluno.alunos.get(i).getDiscplina().getCodigo()
                                .equalsIgnoreCase(disciplina.getCodigo())
                        && Aluno.alunos.get(i).getCiclo().getDescTema()
                                .equalsIgnoreCase(ciclo.getDescTema())
                        && Aluno.alunos.get(i).getCurso().getCodigo().equalsIgnoreCase(curso.getCodigo())){
                    model.addElement(
                        "MATRÍCULA: " + Aluno.alunos.get(i).getMatricula().toUpperCase() +
                         " | NOME: " + Aluno.alunos.get(i).getNome().toUpperCase() + 
                            " | ENDEREÇO: " + Aluno.alunos.get(i).getEndereco().toUpperCase()
                    );   //  
                }
            }
        }
        
        JList<String> list = new JList<>(model); 
        
        list.setFont(new Font("Arial", Font.BOLD, 16));
        
        jListItemClickEvent(list);
               
        return list;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAluno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAluno.setBackground(new java.awt.Color(102, 102, 0));
        labelAluno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelAluno.setForeground(new java.awt.Color(153, 51, 0));
        labelAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAluno.setText("Alunos");
        labelAluno.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 171, 134)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addComponent(labelAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }
    
    private void jListItemClickEvent(JList dataList) {
        
        dataList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                String value = dataList.getSelectedValue().toString();
                labelAluno.setText(value);
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAluno;
    // End of variables declaration//GEN-END:variables
}
