/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import static jFrames.ViewPeriodos.centreWindow;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import sool.*;


public class ViewDisciplinas extends javax.swing.JFrame {

    public Ciclo ciclo;
    public Curso curso;
    private int width = 840;
    private int height = 340;
    public String codDisciplina;
    public boolean isEmpty = false;
    boolean isGraduacao;
    
    public ViewDisciplinas(Ciclo c, Curso curso, boolean isGraduacao) {
        this.ciclo = c;
        this.curso = curso;
        this.isGraduacao = isGraduacao;
        initPanel();
        initComponents();
        centreWindow(this);
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) { 
                new SOOL().setVisible(true);
            }
        });
    }
    
    public void initPanel(){
        add(createMainPanel());
        setTitle("Lista de Disciplinas");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(width, height);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    private JPanel createMainPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(new EmptyBorder(10, 10, 10, 10));
        panel.add(new JScrollPane(showDisciplinas()), BorderLayout.CENTER);
        return panel;
    }
    
    public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }
    
    public JList<String> showDisciplinas(){
        
        DefaultListModel<String> model = new DefaultListModel<>();
        
        System.out.println("Curso passado:(D) " + curso.getNome());
        System.out.println("Ciclo passado:(D) " + ciclo.getDescTema());
        System.out.println("------------------------------------");
        
        Disciplina.disciplinas = new Arquivo().readDisciplinas("d");
        
        if(Disciplina.disciplinas.isEmpty()){
            model.addElement("NENHUMA DISCIPLINA NESSE CICLO!");
        } else {
            for(int i = 0; i < Disciplina.disciplinas.size(); i++){
                if(Disciplina.disciplinas.get(i).getCiclo().getDescTema()
                        .equalsIgnoreCase(ciclo.getDescTema()) &&
                        Disciplina.disciplinas.get(i).getCurso().getCodigo()
                                .equalsIgnoreCase(curso.getCodigo())){
                    model.addElement(
                        "CÓDIGO: " + Disciplina.disciplinas.get(i).getCodigo().toUpperCase() +
                         " | NOME: " + Disciplina.disciplinas.get(i).getNome().toUpperCase() + 
                         " | CARGA HORÁRIA: " + 
                         String.valueOf(Disciplina.disciplinas.get(i).getCargaHoraria()).toUpperCase() +
                         " | CRÉDITOS: " + 
                         String.valueOf(Disciplina.disciplinas.get(i).getQuantCreditos()).toUpperCase() +
                         " | CRÉDITOS MÍNIMOS: " + 
                                String.valueOf(Disciplina.disciplinas.get(i).getQuantMinCreditos()).toUpperCase()
                    );     
                }     
            }    
        }
        
        JList<String> list = new JList<String>(model); 
        
        list.setFont(new Font("Arial", Font.BOLD, 16));
        
        jListItemClickEvent(list);
               
        return list;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewCurses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewCurses.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        viewCurses.setForeground(new java.awt.Color(153, 0, 51));
        viewCurses.setText("Ver Turmas");
        viewCurses.setBorder(new javax.swing.border.MatteBorder(null));
        viewCurses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCursesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewCurses, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addComponent(viewCurses, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewCursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCursesActionPerformed
        for(int i = 0; i < Disciplina.disciplinas.size(); i++){
            if(Disciplina.disciplinas.get(i).getCurso().getCodigo().equalsIgnoreCase(curso.getCodigo())
                    && Disciplina.disciplinas.get(i).getCiclo().
                            getDescTema().equalsIgnoreCase(ciclo.getDescTema())
                    && Disciplina.disciplinas.get(i).getCodigo().equalsIgnoreCase(codDisciplina)){
                ViewTurmas viewTurmas = new ViewTurmas(
                        Disciplina.disciplinas.get(i).getCiclo(),
                        Disciplina.disciplinas.get(i).getCurso(),
                        Disciplina.disciplinas.get(i),
                        isGraduacao);
                viewTurmas.setVisible(true);
                viewTurmas.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                this.setVisible(false);
                System.out.println("-------------------------------------");
                System.out.println("Nome do Curso: " + Disciplina.disciplinas.get(i).getCurso().getNome());
                System.out.println("Ciclo da Disciplina: " + 
                        Disciplina.disciplinas.get(i).getCiclo().getDescTema());
                System.out.println("Nome da Disciplina: " + Disciplina.disciplinas.get(i).getNome());
                break;      
            }     
        } 
    }//GEN-LAST:event_viewCursesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      
    }
    
    private void jListItemClickEvent(JList dataList) {  
        dataList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                String value = dataList.getSelectedValue().toString() + " ";
                if(value.contains(":")){
                    codDisciplina = value
                            .substring(value.indexOf(':') + 1, value.indexOf('|')).trim();    
                    System.out.println("Código da Disciplina: " + codDisciplina); 
                } else {
                    codDisciplina = "";
                    isEmpty = true;
                }
                
            }
        });   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton viewCurses;
    // End of variables declaration//GEN-END:variables
}
